import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://img.freepik.com/free-photo/smart-drone-with-ai-technology_23-2148991437.jpg",
    title: "DJI Phantom 4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1500.00",
    newPrice: "1200",
    company: "abc",
    color: "white",
    category: "agriculture",
    move: "/DJI_Phantom4"
  },
  {
    img: "https://img.freepik.com/free-photo/aerial-drone-sunset_58409-214.jpg",
    title: "Parrot Anafi",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$1400.00",
    newPrice: "1100",
    company: "abc",
    color: "red",
    category: "agriculture",
    move: "/Parrot_Anafi"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-fields_58409-214.jpg",
    title: "DJI Mavic Air 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(97 reviews)",
    prevPrice: "$1350.00",
    newPrice: "1000",
    company: "abc",
    color: "green",
    category: "agriculture",
    move: "/DJI_Mavic_Air2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-sky_58409-216.jpg",
    title: "Autel Robotics EVO",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$1600.00",
    newPrice: "1300",
    company: "pqrs",
    color: "black",
    category: "agriculture",
    move: "/Autel_RoboticsEVO"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-water_58409-217.jpg",
    title: "Yuneec Typhoon H",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$1400.00",
    newPrice: "1200",
    company: "efg",
    color: "green",
    category: "photography",
    move: "/Yuneec_TyphoonH"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-mountains_58409-218.jpg",
    title: "Skydio 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$1800.00",
    newPrice: "1600",
    company: "pqrs",
    color: "black",
    category: "photography",
    move: "/Skydio2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-city_58409-219.jpg",
    title: "DJI Inspire 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$2400.00",
    newPrice: "2200",
    company: "efg",
    color: "white",
    category: "photography",
    move: "/DJI_Inspire2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-forest_58409-220.jpg",
    title: "PowerVision PowerEgg X",
    star: <AiFillStar className="rating-star" />,
    reviews: "(78 reviews)",
    prevPrice: "$1100.00",
    newPrice: "900",
    company: "abc",
    color: "green",
    category: "agriculture",
    move: "/PowerVision_PowerEggX"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-clouds_58409-221.jpg",
    title: "DJI Phantom 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$1000.00",
    newPrice: "800",
    company: "pqrs",
    color: "blue",
    category: "agriculture",
    move: "/DJI_Phantom3"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-above-ground_58409-222.jpg",
    title: "Parrot Bebop 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "$700.00",
    newPrice: "600",
    company: "xyz",
    color: "green",
    category: "agriculture",
    move: "/Parrot_Bebop2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-beach_58409-223.jpg",
    title: "DJI Mavic Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(112 reviews)",
    prevPrice: "$1300.00",
    newPrice: "1100",
    company: "xyz",
    color: "red",
    category: "agriculture",
    move: "/DJI_MavicPro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunset_58409-224.jpg",
    title: "DJI Spark",
    star: <AiFillStar className="rating-star" />,
    reviews: "(117 reviews)",
    prevPrice: "$500.00",
    newPrice: "400",
    company: "xyz",
    color: "black",
    category: "agriculture",
    move: "/DJI_Spark"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-countryside_58409-225.jpg",
    title: "DJI Phantom 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(122 reviews)",
    prevPrice: "$700.00",
    newPrice: "600",
    company: "xyz",
    color: "white",
    category: "agriculture",
    move: "/DJI_Phantom_2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-forest_58409-226.jpg",
    title: "DJI Mini 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$800.00",
    newPrice: "700",
    company: "xyz",
    color: "black",
    category: "agriculture",
    move: "/DJI_Mini_2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-lake_58409-227.jpg",
    title: "Ryze Tello",
    star: <AiFillStar className="rating-star" />,
    reviews: "(65 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    company: "xyz",
    color: "green",
    category: "agriculture",
    move: "/Ryze_Tello"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-field_58409-228.jpg",
    title: "DJI Phantom 1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$400.00",
    newPrice: "300",
    company: "efg",
    color: "red",
    category: "photography",
    move: "/DJI_Phantom_1"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-river_58409-229.jpg",
    title: "DJI Phantom SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$900.00",
    newPrice: "700",
    company: "efg",
    color: "white",
    category: "security",
    move: "/DJI_Phantom_SE"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-road_58409-230.jpg",
    title: "DJI Mavic Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(119 reviews)",
    prevPrice: "$400.00",
    newPrice: "300",
    company: "efg",
    color: "blue",
    category: "security",
    move: "/DJI_Mavic_Mini"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunrise_58409-231.jpg",
    title: "Holy Stone HS720E",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$300.00",
    newPrice: "200",
    company: "abc",
    color: "black",
    category: "security",
    move: "/Holy_Stone_HS720E"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-desert_58409-232.jpg",
    title: "FIMI X8 SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(108 reviews)",
    prevPrice: "$400.00",
    newPrice: "300",
    company: "efg",
    color: "black",
    category: "mining",
    move: "/FIMI_X8_SE"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-beach-sunset_58409-233.jpg",
    title: "Potensic Dreamer Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(115 reviews)",
    prevPrice: "$400.00",
    newPrice: "300",
    company: "xyz",
    color: "black",
    category: "mining",
    move: "/Potensic_Dreamer_Pro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-ocean_58409-234.jpg",
    title: "EACHINE EX5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$200.00",
    newPrice: "150",
    company: "abc",
    color: "red",
    category: "mining",
    move: "/EACHINE_EX5"
  },
];

export default data;
