import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://img.freepik.com/free-photo/smart-drone-with-ai-technology_23-2148991437.jpg",
    title: "DJI Phantom 4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time: "60 min",
    memory: "45",
    category: "agriculture",
    move: "/DJI_Phantom4",
    description: "The DJI Phantom 4 is a versatile drone equipped with advanced AI technology, ideal for capturing high-quality aerial footage. Its intelligent flight modes and robust build make it suitable for both enthusiasts and professionals.",
    weight: "1380 g",
    max_weight_carry: "1300 g",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "6000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/aerial-drone-sunset_58409-214.jpg",
    title: "Parrot Anafi",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$140.00",
    newPrice: "100",
    time: "60 min",
    memory: "20",
    category: "agriculture",
    move: "/Parrot_Anafi",
    description: "The Parrot Anafi is a compact and lightweight drone featuring a 4K HDR camera and powerful flight capabilities. It is designed for both casual and professional use, offering impressive performance and ease of use.",
    weight: "320 g",
    max_weight_carry: "200 g",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3.3 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "4000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-fields_58409-214.jpg",
    title: "DJI Mavic Air 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(97 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time: "60 min",
    memory: "30",
    category: "agriculture",
    move: "/DJI_Mavic_Air2",
    description: "The DJI Mavic Air 2 offers a high-quality camera and advanced flight features, making it a great choice for both casual and professional drone enthusiasts. It combines excellent flight performance with compact design.",
    weight: "570 g",
    max_weight_carry: "500 g",
    max_ascent_speed: "6 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "19 m/s",
    max_ceiling: "5000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-sky_58409-216.jpg",
    title: "Autel Robotics EVO",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$600.00",
    newPrice: "200",
    time: "150 min",
    memory: "10",
    category: "agriculture",
    move: "/Autel_RoboticsEVO",
    description: "The Autel Robotics EVO features robust build quality and impressive flight time, along with 4K camera capabilities. It's designed for serious aerial photographers and drone pilots.",
    weight: "861 g",
    max_weight_carry: "800 g",
    max_ascent_speed: "7 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "25 m/s",
    max_ceiling: "7000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-water_58409-217.jpg",
    title: "Yuneec Typhoon H",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time: "120 min",
    memory: "30",
    category: "photography",
    move: "/Yuneec_TyphoonH",
    description: "The Yuneec Typhoon H is equipped with a 4K camera and offers smooth flight performance. It's perfect for high-quality aerial photography with its six-rotor design.",
    weight: "1500 g",
    max_weight_carry: "1400 g",
    max_ascent_speed: "4.5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "5000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-mountains_58409-218.jpg",
    title: "Skydio 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$180.00",
    newPrice: "150",
    time: "150 min",
    memory: "10",
    category: "photography",
    move: "/Skydio2",
    description: "The Skydio 2 is known for its advanced obstacle avoidance and autonomous flying capabilities, making it ideal for capturing complex and dynamic footage.",
    weight: "775 g",
    max_weight_carry: "700 g",
    max_ascent_speed: "5.5 m/s",
    max_descent_speed: "4.5 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "4000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-city_58409-219.jpg",
    title: "DJI Inspire 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time: "120 min",
    memory: "45",
    category: "photography",
    move: "/DJI_Inspire2",
    description: "The DJI Inspire 2 combines a high-performance camera with advanced flight features, ideal for professional filmmakers and photographers seeking superior image quality.",
    weight: "3440 g",
    max_weight_carry: "3000 g",
    max_ascent_speed: "6 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "18 m/s",
    max_ceiling: "7000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-forest_58409-220.jpg",
    title: "PowerVision PowerEgg X",
    star: <AiFillStar className="rating-star" />,
    reviews: "(78 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    time: "60 min",
    memory: "30",
    category: "agriculture",
    move: "/PowerVision_PowerEggX",
    description: "The PowerVision PowerEgg X offers a unique design and solid performance with a 4K camera. It is well-suited for various environmental conditions and agricultural use.",
    weight: "865 g",
    max_weight_carry: "750 g",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "3.5 m/s",
    max_forward_speed: "14 m/s",
    max_ceiling: "4500 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-clouds_58409-221.jpg",
    title: "DJI Phantom 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    time: "150 min",
    memory: "45",
    category: "agriculture",
    move: "/DJI_Phantom3",
    description: "The DJI Phantom 3 is known for its reliability and ease of use. It features a 4K camera and strong flight capabilities, making it a solid choice for aerial photography.",
    weight: "1280 g",
    max_weight_carry: "1100 g",
    max_ascent_speed: "4.8 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "6000 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-above-ground_58409-222.jpg",
    title: "Parrot Bebop 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "$700.00",
    newPrice: "200",
    time: "90 min",
    memory: "30",
    category: "agriculture",
    move: "/Parrot_Bebop2",
    description: "The Parrot Bebop 2 offers a compact design and a 14MP camera with high-quality video recording. It is designed for users who need reliable performance in a lightweight package.",
    weight: "500 g",
    max_weight_carry: "400 g",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "3500 m"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-countryside_58409-225.jpg",
    title: "DJI Phantom 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(122 reviews)",
    prevPrice: "$700.00",
    newPrice: "150",
    time: "90 min",
    memory: "45",
    category: "agriculture",
    move: "/DJI_Phantom_2",
    description: "The DJI Phantom 2 is a powerful drone designed for aerial photography and videography. It features enhanced stability and easy-to-use controls, making it ideal for capturing high-quality images and videos in various environments.",
    weight: "1.2 kg",
    max_weight_carry: "1 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "2000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-forest_58409-226.jpg",
    title: "DJI Mini 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$200.00",
    newPrice: "50",
    time: "90 min",
    memory: "10",
    category: "agriculture",
    move: "/DJI_Mini_2",
    description: "Compact yet powerful, the DJI Mini 2 offers impressive flight capabilities and high-resolution camera performance. It's perfect for enthusiasts looking for a portable drone that delivers exceptional quality in a small package.",
    weight: "249 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-lake_58409-227.jpg",
    title: "Ryze Tello",
    star: <AiFillStar className="rating-star" />,
    reviews: "(65 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time: "90 min",
    memory: "30",
    category: "agriculture",
    move: "/Ryze_Tello",
    description: "The Ryze Tello is an entry-level drone designed for both beginners and casual users. With its user-friendly interface and stable flight performance, it’s an excellent choice for those looking to get started with aerial photography.",
    weight: "80 g",
    max_weight_carry: "0.1 kg",
    max_ascent_speed: "2.8 m/s",
    max_descent_speed: "2.2 m/s",
    max_forward_speed: "8 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-field_58409-228.jpg",
    title: "DJI Phantom 1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$400.00",
    newPrice: "50",
    time: "120 min",
    memory: "20",
    category: "photography",
    move: "/DJI_Phantom_1",
    description: "The DJI Phantom 1 is a robust drone equipped with a high-quality camera and advanced stabilization features. It is well-suited for capturing stable, clear aerial footage and is known for its reliability and performance.",
    weight: "1.5 kg",
    max_weight_carry: "0.7 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "2000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-river_58409-229.jpg",
    title: "DJI Phantom SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time: "120 min",
    memory: "45",
    category: "security",
    move: "/DJI_Phantom_SE",
    description: "The DJI Phantom SE offers a perfect blend of performance and affordability. It features advanced flight modes and a high-resolution camera, making it suitable for both professional and recreational use.",
    weight: "1.3 kg",
    max_weight_carry: "1 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-road_58409-230.jpg",
    title: "DJI Mavic Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(119 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time: "120 min",
    memory: "45",
    category: "security",
    move: "/DJI_Mavic_Mini",
    description: "The DJI Mavic Mini is known for its compact size and powerful performance. With a 4K camera and a range of intelligent flight modes, it’s ideal for capturing stunning aerial shots and videos.",
    weight: "249 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunrise_58409-231.jpg",
    title: "Holy Stone HS720E",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$300.00",
    newPrice: "150",
    time: "60 min",
    memory: "10",
    category: "security",
    move: "/Holy_Stone_HS720E",
    description: "The Holy Stone HS720E offers a range of features including a 4K camera, GPS stability, and intelligent flight modes. It’s designed for both hobbyists and enthusiasts seeking quality performance in a budget-friendly package.",
    weight: "1 kg",
    max_weight_carry: "0.7 kg",
    max_ascent_speed: "3 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "2000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-desert_58409-232.jpg",
    title: "FIMI X8 SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(108 reviews)",
    prevPrice: "$400.00",
    newPrice: "50",
    time: "120 min",
    memory: "10",
    category: "mining",
    move: "/FIMI_X8_SE",
    description: "The FIMI X8 SE is a feature-rich drone with a high-quality camera and extended flight time. It’s perfect for capturing detailed aerial imagery and offers excellent stability and performance in various conditions.",
    weight: "1.3 kg",
    max_weight_carry: "0.8 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "5000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-beach-sunset_58409-233.jpg",
    title: "Potensic Dreamer Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(115 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time: "90 min",
    memory: "10",
    category: "mining",
    move: "/Potensic_Dreamer_Pro",
    description: "The Potensic Dreamer Pro combines a sleek design with powerful performance. Featuring a 4K camera and various intelligent flight modes, it’s suitable for capturing high-quality aerial footage at an affordable price.",
    weight: "950 g",
    max_weight_carry: "0.6 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-ocean_58409-234.jpg",
    title: "EACHINE EX5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$200.00",
    newPrice: "150",
    time: "60 min",
    memory: "20",
    category: "mining",
    move: "/EACHINE_EX5",
    description: "The EACHINE EX5 is a versatile drone that offers a balance of performance and affordability. With a high-resolution camera and a range of smart flight features, it’s ideal for both beginners and seasoned pilots.",
    weight: "700 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "14 m/s",
    max_ceiling: "2500 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-cityscape_58409-235.jpg",
    title: "Hubsan Zino Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(80 reviews)",
    prevPrice: "$900.00",
    newPrice: "50",
    time: "120 min",
    memory: "30",
    category: "photography",
    move: "/Hubsan_Zino_Pro",
    description: "The Hubsan Zino Pro is a high-performance drone with a 4K camera and advanced flight features. It offers a long flight time and excellent image quality, making it a great choice for aerial photography enthusiasts.",
    weight: "1.2 kg",
    max_weight_carry: "1 kg",
    max_ascent_speed: "6 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "18 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-clouds_58409-236.jpg",
    title: "Tello Iron Man Edition",
    star: <AiFillStar className="rating-star" />,
    reviews: "(55 reviews)",
    prevPrice: "$200.00",
    newPrice: "150",
    time: "60 min",
    memory: "20",
    category: "security",
    move: "/Tello_Iron_Man_Edition",
    description: "The Tello Iron Man Edition is a limited edition drone offering a unique design and solid performance. With a high-definition camera and easy-to-use controls, it's perfect for both recreational and creative aerial shooting.",
    weight: "80 g",
    max_weight_carry: "0.1 kg",
    max_ascent_speed: "2.8 m/s",
    max_descent_speed: "2.2 m/s",
    max_forward_speed: "8 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-harvest_58409-237.jpg",
    title: "Xiaomi Mi Drone 4K",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$450.00",
    newPrice: "100",
    time: "120 min",
    memory: "10",
    category: "agriculture",
    move: "/Xiaomi_Mi_Drone_4K",
    description: "The Xiaomi Mi Drone 4K is a powerful and versatile drone with a high-resolution camera and long battery life. Ideal for agricultural monitoring and aerial photography, it delivers excellent performance and image quality.",
    weight: "1.4 kg",
    max_weight_carry: "1 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "4000 meters"
  },  
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-forest_58409-238.jpg",
    title: "DJI Air 2S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(135 reviews)",
    prevPrice: "$1000.00",
    newPrice: "150",
    time: "150 min",
    memory: "40",
    category: "photography",
    move: "/DJI_Air_2S",
    description: "The DJI Air 2S offers an impressive combination of performance and image quality. Equipped with a 1-inch CMOS sensor, it captures stunning 5.4K video and 20MP photos. It also features advanced obstacle avoidance and intelligent shooting modes.",
    weight: "595 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "19 m/s",
    max_ceiling: "5000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-field_58409-239.jpg",
    title: "Hubsan X4 H501S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(65 reviews)",
    prevPrice: "$300.00",
    newPrice: "150",
    time: "90 min",
    memory: "45",
    category: "mining",
    move: "/Hubsan_X4_H501S",
    description: "The Hubsan X4 H501S is a reliable drone with GPS capabilities and a 1080p HD camera. It's well-suited for mining and industrial inspections, offering stable flight and precise control even in challenging conditions.",
    weight: "320 g",
    max_weight_carry: "0.3 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-harvest-fields_58409-240.jpg",
    title: "Holy Stone HS100",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$350.00",
    newPrice: "200",
    time: "60 min",
    memory: "45",
    category: "agriculture",
    move: "/Holy_Stone_HS100",
    description: "The Holy Stone HS100 features a GPS-assisted flight system and a 1080p HD camera. It's designed for agricultural monitoring with reliable stability and intelligent flight modes to capture detailed aerial views.",
    weight: "700 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "3 m/s",
    max_descent_speed: "2.5 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "2000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-cloudy-sky_58409-241.jpg",
    title: "Walkera Vitus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(70 reviews)",
    prevPrice: "$600.00",
    newPrice: "200",
    time: "120 min",
    memory: "30",
    category: "security",
    move: "/Walkera_Vitus",
    description: "The Walkera Vitus offers a robust design and high-quality camera for security applications. With its 4K video recording and intelligent flight modes, it provides excellent surveillance capabilities and easy control.",
    weight: "980 g",
    max_weight_carry: "0.8 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-forest-mountains_58409-242.jpg",
    title: "Yuneec Mantis Q",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$500.00",
    newPrice: "100",
    time: "60 min",
    memory: "10",
    category: "photography",
    move: "/Yuneec_Mantis_Q",
    description: "The Yuneec Mantis Q is a compact drone with a 4K camera, designed for high-quality aerial photography. It features voice control and intelligent flight modes, making it a great choice for capturing stunning visuals.",
    weight: "500 g",
    max_weight_carry: "0.4 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-ice_58409-243.jpg",
    title: "GDU O2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$700.00",
    newPrice: "50",
    time: "120 min",
    memory: "40",
    category: "mining",
    move: "/GDU_O2",
    description: "The GDU O2 is a versatile drone with a 4K camera and robust build, ideal for mining inspections. It offers long flight times and high stability, providing clear and detailed images even in challenging conditions.",
    weight: "950 g",
    max_weight_carry: "0.7 kg",
    max_ascent_speed: "6 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "18 m/s",
    max_ceiling: "5000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-desert_58409-244.jpg",
    title: "Ryze Tello EDU",
    star: <AiFillStar className="rating-star" />,
    reviews: "(75 reviews)",
    prevPrice: "$180.00",
    newPrice: "100",
    time: "60 min",
    memory: "10",
    category: "education",
    move: "/Ryze_Tello_EDU",
    description: "The Ryze Tello EDU is an educational drone designed for learning and experimentation. It offers a 720p HD camera and programmable features, making it an excellent tool for teaching the basics of drone technology and coding.",
    weight: "80 g",
    max_weight_carry: "0.1 kg",
    max_ascent_speed: "2.8 m/s",
    max_descent_speed: "2.5 m/s",
    max_forward_speed: "8 m/s",
    max_ceiling: "3000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-rice-fields_58409-245.jpg",
    title: "FIMI X8 Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$350.00",
    newPrice: "150",
    time: "90 min",
    memory: "20",
    category: "agriculture",
    move: "/FIMI_X8_Mini",
    description: "The FIMI X8 Mini is a compact drone with impressive performance for agricultural applications. It features a 4K camera and intelligent flight modes, making it ideal for crop monitoring and aerial surveys.",
    weight: "260 g",
    max_weight_carry: "0.3 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "14 m/s",
    max_ceiling: "4000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-lake-sunset_58409-246.jpg",
    title: "EACHINE E58",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$250.00",
    newPrice: "200",
    time: "60 min",
    memory: "45",
    category: "security",
    move: "/EACHINE_E58",
    description: "The EACHINE E58 is a foldable drone with a 720p HD camera and a compact design. It's perfect for security applications and casual flying, offering easy portability and reliable performance.",
    weight: "300 g",
    max_weight_carry: "0.2 kg",
    max_ascent_speed: "3 m/s",
    max_descent_speed: "2.5 m/s",
    max_forward_speed: "12 m/s",
    max_ceiling: "2500 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-countryside_58409-247.jpg",
    title: "Hubsan Zino Mini Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$500.00",
    newPrice: "200",
    time: "120 min",
    memory: "30",
    category: "mining",
    move: "/Hubsan_Zino_Mini_Pro",
    description: "The Hubsan Zino Mini Pro is a compact drone with advanced features for mining and industrial inspections. It offers a 4K camera, long battery life, and reliable performance in various environments.",
    weight: "450 g",
    max_weight_carry: "0.4 kg",
    max_ascent_speed: "4 m/s",
    max_descent_speed: "3.5 m/s",
    max_forward_speed: "15 m/s",
    max_ceiling: "5000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunset_58409-248.jpg",
    title: "DJI Mavic Air 2S Fly More Combo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(140 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time: "150 min",
    memory: "40",
    category: "photography",
    move: "/DJI_Mavic_Air2S_Fly_More_Combo",
    description: "The DJI Mavic Air 2S Fly More Combo provides exceptional performance with a 1-inch sensor and 5.4K video capabilities. It includes extra batteries and accessories, making it perfect for extended photography sessions.",
    weight: "595 g",
    max_weight_carry: "0.5 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "19 m/s",
    max_ceiling: "5000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-mountains-sky_58409-249.jpg",
    title: "Autel Robotics X-Star Premium",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    prevPrice: "$800.00",
    newPrice: "150",
    time: "120 min",
    memory: "20",
    category: "photography",
    move: "/Autel_Robotics_X-Star_Premium",
    description: "The Autel Robotics X-Star Premium offers high-quality 4K video and advanced flight features. It's built for professional photographers and videographers seeking superior image quality and flight stability.",
    weight: "1.2 kg",
    max_weight_carry: "0.8 kg",
    max_ascent_speed: "6 m/s",
    max_descent_speed: "5 m/s",
    max_forward_speed: "20 m/s",
    max_ceiling: "6000 meters"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-city_58409-250.jpg",
    title: "Parrot Anafi FPV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$550.00",
    newPrice: "200",
    time: "90 min",
    memory: "10",
    category: "security",
    move: "/Parrot_Anafi_FPV",
    description: "The Parrot Anafi FPV offers a unique first-person view experience with its 4K HDR camera. Designed for security applications, it provides high-quality video and excellent maneuverability.",
    weight: "320 g",
    max_weight_carry: "0.3 kg",
    max_ascent_speed: "5 m/s",
    max_descent_speed: "4 m/s",
    max_forward_speed: "16 m/s",
    max_ceiling: "3500 meters"
  }, 
];

export default data;
