import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://img.freepik.com/free-photo/smart-drone-with-ai-technology_23-2148991437.jpg",
    title: "DJI Phantom 4",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time : "60 min",
    memory : "45",
    category: "agriculture",
    move: "/DJI_Phantom4"
  },
  {
    img: "https://img.freepik.com/free-photo/aerial-drone-sunset_58409-214.jpg",
    title: "Parrot Anafi",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$140.00",
    newPrice: "100",
    time : "60 min",
    memory : "20",
    category: "agriculture",
    move: "/Parrot_Anafi"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-fields_58409-214.jpg",
    title: "DJI Mavic Air 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(97 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time : "60 min",
    memory : "30",
    category: "agriculture",
    move: "/DJI_Mavic_Air2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-sky_58409-216.jpg",
    title: "Autel Robotics EVO",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$600.00",
    newPrice: "200",
    time : "150 min",
    memory : "10",
    category: "agriculture",
    move: "/Autel_RoboticsEVO"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-water_58409-217.jpg",
    title: "Yuneec Typhoon H",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time : "120 min",
    memory : "30",
    category: "photography",
    move: "/Yuneec_TyphoonH"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-mountains_58409-218.jpg",
    title: "Skydio 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$180.00",
    newPrice: "150",
    time : "150 min",
    memory : "10",
    category: "photography",
    move: "/Skydio2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-city_58409-219.jpg",
    title: "DJI Inspire 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time : "120 min",
    memory : "45",
    category: "photography",
    move: "/DJI_Inspire2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-forest_58409-220.jpg",
    title: "PowerVision PowerEgg X",
    star: <AiFillStar className="rating-star" />,
    reviews: "(78 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    time : "60 min",
    memory : "30",
    category: "agriculture",
    move: "/PowerVision_PowerEggX"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-clouds_58409-221.jpg",
    title: "DJI Phantom 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$100.00",
    newPrice: "50",
    time : "150 min",
    memory : "45",
    category: "agriculture",
    move: "/DJI_Phantom3"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-above-ground_58409-222.jpg",
    title: "Parrot Bebop 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "$700.00",
    newPrice: "200",
    time : "90 min",
    memory : "30",
    category: "agriculture",
    move: "/Parrot_Bebop2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-beach_58409-223.jpg",
    title: "DJI Mavic Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(112 reviews)",
    prevPrice: "$300.00",
    newPrice: "200",
    time : "90 min",
    memory : "20",
    category: "agriculture",
    move: "/DJI_MavicPro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunset_58409-224.jpg",
    title: "DJI Spark",
    star: <AiFillStar className="rating-star" />,
    reviews: "(117 reviews)",
    prevPrice: "$500.00",
    newPrice: "150",
    time : "90 min",
    memory : "10",
    category: "agriculture",
    move: "/DJI_Spark"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-countryside_58409-225.jpg",
    title: "DJI Phantom 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(122 reviews)",
    prevPrice: "$700.00",
    newPrice: "150",
    time : "90 min",
    memory : "45",
    category: "agriculture",
    move: "/DJI_Phantom_2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-forest_58409-226.jpg",
    title: "DJI Mini 2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(150 reviews)",
    prevPrice: "$200.00",
    newPrice: "50",
    time : "90 min",
    memory : "10",
    category: "agriculture",
    move: "/DJI_Mini_2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-lake_58409-227.jpg",
    title: "Ryze Tello",
    star: <AiFillStar className="rating-star" />,
    reviews: "(65 reviews)",
    prevPrice: "$150.00",
    newPrice: "100",
    time : "90 min",
    memory : "30",
    category: "agriculture",
    move: "/Ryze_Tello"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-field_58409-228.jpg",
    title: "DJI Phantom 1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$400.00",
    newPrice: "50",
    time : "120 min",
    memory : "20",
    category: "photography",
    move: "/DJI_Phantom_1"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-river_58409-229.jpg",
    title: "DJI Phantom SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time : "120 min",
    memory : "45",
    category: "security",
    move: "/DJI_Phantom_SE"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-road_58409-230.jpg",
    title: "DJI Mavic Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(119 reviews)",
    prevPrice: "$400.00",
    newPrice: "200",
    time : "120 min",
    memory : "45",
    category: "security",
    move: "/DJI_Mavic_Mini"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunrise_58409-231.jpg",
    title: "Holy Stone HS720E",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$300.00",
    newPrice: "150",
    time : "60 min",
    memory : "10",
    category: "security",
    move: "/Holy_Stone_HS720E"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-desert_58409-232.jpg",
    title: "FIMI X8 SE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(108 reviews)",
    prevPrice: "$400.00",
    newPrice: "50",
    time : "120 min",
    memory : "10",
    category: "mining",
    move: "/FIMI_X8_SE"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-beach-sunset_58409-233.jpg",
    title: "Potensic Dreamer Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(115 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time : "90 min",
    memory : "10",
    category: "mining",
    move: "/Potensic_Dreamer_Pro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-ocean_58409-234.jpg",
    title: "EACHINE EX5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$200.00",
    newPrice: "150",
    time : "60 min",
    memory : "20",
    category: "mining",
    move: "/EACHINE_EX5"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-cityscape_58409-235.jpg",
    title: "Hubsan Zino Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(80 reviews)",
    prevPrice: "$900.00",
    newPrice: "50",
    time : "120 min",
    memory : "30",
    category: "photography",
    move: "/Hubsan_Zino_Pro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-clouds_58409-236.jpg",
    title: "Tello Iron Man Edition",
    star: <AiFillStar className="rating-star" />,
    reviews: "(55 reviews)",
    prevPrice: "$200.00",
    newPrice: "150",
    time : "60 min",
    memory : "20",
    category: "security",
    move: "/Tello_Iron_Man_Edition"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-harvest_58409-237.jpg",
    title: "Xiaomi Mi Drone 4K",
    star: <AiFillStar className="rating-star" />,
    reviews: "(110 reviews)",
    prevPrice: "$450.00",
    newPrice: "100",
    time : "120 min",
    memory : "10",
    category: "agriculture",
    move: "/Xiaomi_Mi_Drone_4K"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-forest_58409-238.jpg",
    title: "DJI Air 2S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(135 reviews)",
    prevPrice: "$1000.00",
    newPrice: "150",
    time : "150 min",
    memory : "40",
    category: "photography",
    move: "/DJI_Air_2S"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-field_58409-239.jpg",
    title: "Hubsan X4 H501S",
    star: <AiFillStar className="rating-star" />,
    reviews: "(65 reviews)",
    prevPrice: "$300.00",
    newPrice: "150",
    time : "90 min",
    memory : "45",
    category: "mining",
    move: "/Hubsan_X4_H501S"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-above-harvest-fields_58409-240.jpg",
    title: "Holy Stone HS100",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$350.00",
    newPrice: "200",
    time : "60 min",
    memory : "45",
    category: "agriculture",
    move: "/Holy_Stone_HS100"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-cloudy-sky_58409-241.jpg",
    title: "Walkera Vitus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(70 reviews)",
    prevPrice: "$600.00",
    newPrice: "200",
    time : "120 min",
    memory : "30",
    category: "security",
    move: "/Walkera_Vitus"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-forest-mountains_58409-242.jpg",
    title: "Yuneec Mantis Q",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$500.00",
    newPrice: "100",
    time : "60 min",
    memory : "10",
    category: "photography",
    move: "/Yuneec_Mantis_Q"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-over-ice_58409-243.jpg",
    title: "GDU O2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(90 reviews)",
    prevPrice: "$700.00",
    newPrice: "50",
    time : "120 min",
    memory : "40",
    category: "mining",
    move: "/GDU_O2"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-desert_58409-244.jpg",
    title: "Ryze Tello EDU",
    star: <AiFillStar className="rating-star" />,
    reviews: "(75 reviews)",
    prevPrice: "$180.00",
    newPrice: "100",
    time : "60 min",
    memory : "10",
    category: "education",
    move: "/Ryze_Tello_EDU"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-over-rice-fields_58409-245.jpg",
    title: "FIMI X8 Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "(95 reviews)",
    prevPrice: "$350.00",
    newPrice: "150",
    time : "90 min",
    memory : "20",
    category: "agriculture",
    move: "/FIMI_X8_Mini"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-lake-sunset_58409-246.jpg",
    title: "EACHINE E58",
    star: <AiFillStar className="rating-star" />,
    reviews: "(85 reviews)",
    prevPrice: "$250.00",
    newPrice: "200",
    time : "60 min",
    memory : "45",
    category: "security",
    move: "/EACHINE_E58"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-flying-countryside_58409-247.jpg",
    title: "Hubsan Zino Mini Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$500.00",
    newPrice: "200",
    time : "120 min",
    memory : "30",
    category: "mining",
    move: "/Hubsan_Zino_Mini_Pro"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-sunset_58409-248.jpg",
    title: "DJI Mavic Air 2S Fly More Combo",
    star: <AiFillStar className="rating-star" />,
    reviews: "(140 reviews)",
    prevPrice: "$120.00",
    newPrice: "50",
    time : "150 min",
    memory : "40",
    category: "photography",
    move: "/DJI_Mavic_Air2S_Fly_More_Combo"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-mountains-sky_58409-249.jpg",
    title: "Autel Robotics X-Star Premium",
    star: <AiFillStar className="rating-star" />,
    reviews: "(120 reviews)",
    prevPrice: "$800.00",
    newPrice: "150",
    time : "120 min",
    memory : "20",
    category: "photography",
    move: "/Autel_Robotics_X-Star_Premium"
  },
  {
    img: "https://img.freepik.com/free-photo/drone-hovering-city_58409-250.jpg",
    title: "Parrot Anafi FPV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(105 reviews)",
    prevPrice: "$550.00",
    newPrice: "200",
    time : "90 min",
    memory : "10",
    category: "security",
    move: "/Parrot_Anafi_FPV"
  },
];

export default data;
